### ISSUE TITLE
Moonlight stopped working after update

### ISSUE THREAD

**Issue by stephen322** [maxiberta/moonlight-snap#13]
Last working version was 870.
Possibly apparmor related, but also segfaults:

00:00:00 - Qt Warning: propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.8159\" (uid=1000 pid=28297 comm=\"/snap/moonlight/975/usr/bin/moonlight \" label=\"snap.moonlight.moonlight (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1186 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
00:00:00 - Qt Warning: nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.8159\" (uid=1000 pid=28297 comm=\"/snap/moonlight/975/usr/bin/moonlight \" label=\"snap.moonlight.moonlight (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1186 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
00:00:00 - Qt Warning: "Object path cannot be empty"
00:00:00 - Qt Debug: Current Moonlight version: "2.2.0"
Segmentation fault (core dumped)

**Comment by maxiberta** [comment]
Hi! Those warnings are harmless and should not be related to the segfault. Revision 870 was the last stable amd64 snap based on `core18`, afaict. Revision 887 (v2.1.0) migrated to `core20`, and it was followed by the current r975 (v2.2.0):

```sh
$ snapcraft list-revisions moonlight | grep stable | grep amd64 | head -3
975     2020-09-10T14:25:36Z  amd64   2.2.0               candidate*, stable*
887     2020-06-28T04:09:21Z  amd64   2.1.0               candidate, stable
870     2020-06-17T13:22:57Z  amd64   2.1.0               candidate, stable
```

- Are there any relevant messages on `dmesg` or `journalctl`?
- What's the output of `snap version`?
- What's the output of `snap list core20 moonlight`?
- Do any other snaps based on `core20` work in your system? Eg. `htop`, `black`, `telegram-desktop`.

Thanks!

**Comment by stephen322** [comment]
$ snap version
snap    2.46.1+18.04
snapd   2.46.1+18.04
series  16
ubuntu  18.04
kernel  5.0.0-37-generic


$ snap list core20 moonlight
Name       Version  Rev  Tracking       Publisher   Notes
core20     20       634  latest/stable  canonical✓  base
moonlight  2.2.0    975  latest/stable  maxiberta   -

I haven't tested other core20 apps, but may give that a try.
It's worth noting that Moonlight-2.2.0-x86_64.AppImage works.

More Apparmor DENIEDs in journalctl and dmesg:
journalctl:
Sep 28 13:03:35 coffee audit[4907]: SECCOMP auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=4907 comm="glxinfo" exe="/snap/moonlight/975/usr/bin/glxinfo" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7f33108796e1 code=0x50000
Sep 28 13:03:35 coffee kernel: kauditd_printk_skb: 11 callbacks suppressed
Sep 28 13:03:35 coffee kernel: audit: type=1326 audit(1601312615.730:808): auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=4907 comm="glxinfo" exe="/snap/moonlight/975/usr/bin/glxinfo" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7
Sep 28 13:03:35 coffee kernel: audit: type=1326 audit(1601312615.730:809): auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=4907 comm="glxinfo" exe="/snap/moonlight/975/usr/bin/glxinfo" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7
Sep 28 13:03:35 coffee kernel: audit: type=1326 audit(1601312615.730:810): auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=4907 comm="glxinfo" exe="/snap/moonlight/975/usr/bin/glxinfo" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7
Sep 28 13:03:35 coffee kernel: audit: type=1326 audit(1601312615.730:811): auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=4907 comm="glxinfo" exe="/snap/moonlight/975/usr/bin/glxinfo" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7
Sep 28 13:03:35 coffee audit[4907]: SECCOMP auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=4907 comm="glxinfo" exe="/snap/moonlight/975/usr/bin/glxinfo" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7f33108796e1 code=0x50000
Sep 28 13:03:35 coffee audit[4907]: SECCOMP auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=4907 comm="glxinfo" exe="/snap/moonlight/975/usr/bin/glxinfo" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7f33108796e1 code=0x50000
Sep 28 13:03:35 coffee audit[4907]: SECCOMP auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=4907 comm="glxinfo" exe="/snap/moonlight/975/usr/bin/glxinfo" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7f33108796e1 code=0x50000
Sep 28 13:03:35 coffee audit[4907]: AVC apparmor="DENIED" operation="open" profile="snap.moonlight.moonlight" name="/proc/sys/dev/i915/perf_stream_paranoid" pid=4907 comm="glxinfo" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Sep 28 13:03:35 coffee kernel: audit: type=1400 audit(1601312615.734:812): apparmor="DENIED" operation="open" profile="snap.moonlight.moonlight" name="/proc/sys/dev/i915/perf_stream_paranoid" pid=4907 comm="glxinfo" requested_mask="r" de
Sep 28 13:03:35 coffee audit[4809]: SECCOMP auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=4809 comm="moonlight" exe="/snap/moonlight/975/usr/bin/moonlight" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7f348368f6e1 code=0x50000
Sep 28 13:03:35 coffee audit[4809]: SECCOMP auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=4809 comm="moonlight" exe="/snap/moonlight/975/usr/bin/moonlight" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7f348368f6e1 code=0x50000
Sep 28 13:03:35 coffee audit[4809]: SECCOMP auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=4809 comm="moonlight" exe="/snap/moonlight/975/usr/bin/moonlight" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7f348368f6e1 code=0x50000
Sep 28 13:03:35 coffee audit[4809]: SECCOMP auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=4809 comm="moonlight" exe="/snap/moonlight/975/usr/bin/moonlight" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7f348368f6e1 code=0x50000
Sep 28 13:03:35 coffee audit[4809]: AVC apparmor="DENIED" operation="open" profile="snap.moonlight.moonlight" name="/proc/sys/dev/i915/perf_stream_paranoid" pid=4809 comm="moonlight" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Sep 28 13:03:35 coffee kernel: audit: type=1326 audit(1601312615.826:813): auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=4809 comm="moonlight" exe="/snap/moonlight/975/usr/bin/moonlight" sig=0 arch=c000003e syscall=203 compat=0 ip
Sep 28 13:03:35 coffee kernel: audit: type=1326 audit(1601312615.826:814): auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=4809 comm="moonlight" exe="/snap/moonlight/975/usr/bin/moonlight" sig=0 arch=c000003e syscall=203 compat=0 ip
Sep 28 13:03:35 coffee kernel: audit: type=1326 audit(1601312615.826:815): auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=4809 comm="moonlight" exe="/snap/moonlight/975/usr/bin/moonlight" sig=0 arch=c000003e syscall=203 compat=0 ip
Sep 28 13:03:35 coffee kernel: audit: type=1326 audit(1601312615.826:816): auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=4809 comm="moonlight" exe="/snap/moonlight/975/usr/bin/moonlight" sig=0 arch=c000003e syscall=203 compat=0 ip
Sep 28 13:03:35 coffee kernel: audit: type=1400 audit(1601312615.826:817): apparmor="DENIED" operation="open" profile="snap.moonlight.moonlight" name="/proc/sys/dev/i915/perf_stream_paranoid" pid=4809 comm="moonlight" requested_mask="r" 
Sep 28 13:03:35 coffee dbus-daemon[2112]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/org/a11y/bus" interface="org.freedesktop.DBus.Properties" member="Get" mask="send" name="org.a11y.Bus" pid=4809 label="snap.mo
Sep 28 13:03:35 coffee audit[4809]: SECCOMP auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=4809 comm="moonlight" exe="/snap/moonlight/975/usr/bin/moonlight" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7f348368f6e1 code=0x50000
Sep 28 13:03:35 coffee audit[4809]: SECCOMP auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=4809 comm="moonlight" exe="/snap/moonlight/975/usr/bin/moonlight" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7f348368f6e1 code=0x50000
Sep 28 13:03:35 coffee audit[4809]: SECCOMP auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=4809 comm="moonlight" exe="/snap/moonlight/975/usr/bin/moonlight" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7f348368f6e1 code=0x50000
Sep 28 13:03:35 coffee audit[4809]: SECCOMP auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=4809 comm="moonlight" exe="/snap/moonlight/975/usr/bin/moonlight" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7f348368f6e1 code=0x50000
Sep 28 13:03:35 coffee audit[4809]: AVC apparmor="DENIED" operation="open" profile="snap.moonlight.moonlight" name="/proc/sys/dev/i915/perf_stream_paranoid" pid=4809 comm="moonlight" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Sep 28 13:03:35 coffee audit[1166]: USER_AVC pid=1166 uid=103 auid=4294967295 ses=4294967295 msg='apparmor="DENIED" operation="dbus_method_call"  bus="system" path="/org/freedesktop/NetworkManager" interface="org.freedesktop.DBus.Propert
                                     exe="/usr/bin/dbus-daemon" sauid=103 hostname=? addr=? terminal=?'
Sep 28 13:03:35 coffee audit[1166]: USER_AVC pid=1166 uid=103 auid=4294967295 ses=4294967295 msg='apparmor="DENIED" operation="dbus_method_call"  bus="system" path="/org/freedesktop/NetworkManager" interface="org.freedesktop.NetworkManag
                                     exe="/usr/bin/dbus-daemon" sauid=103 hostname=? addr=? terminal=?'
Sep 28 13:03:35 coffee audit[1166]: USER_AVC pid=1166 uid=103 auid=4294967295 ses=4294967295 msg='apparmor="DENIED" operation="dbus_method_call"  bus="system" path="/org/freedesktop/NetworkManager/Settings" interface="org.freedesktop.Net
                                     exe="/usr/bin/dbus-daemon" sauid=103 hostname=? addr=? terminal=?'
Sep 28 13:03:35 coffee audit[1166]: USER_AVC pid=1166 uid=103 auid=4294967295 ses=4294967295 msg='apparmor="DENIED" operation="dbus_method_call"  bus="system" path="/org/freedesktop/NetworkManager/Settings" interface="org.freedesktop.Net
                                     exe="/usr/bin/dbus-daemon" sauid=103 hostname=? addr=? terminal=?'
Sep 28 13:03:35 coffee audit[1166]: USER_AVC pid=1166 uid=103 auid=4294967295 ses=4294967295 msg='apparmor="DENIED" operation="dbus_method_call"  bus="system" path="/org/freedesktop/NetworkManager/Settings" interface="org.freedesktop.Net
                                     exe="/usr/bin/dbus-daemon" sauid=103 hostname=? addr=? terminal=?'


From dmesg, only the graphics DENIEDs showed up:
$ dmesg -T | grep DENIED
...
[Mon Sep 28 13:04:55 2020] audit: type=1400 audit(1601312615.734:812): apparmor="DENIED" operation="open" profile="snap.moonlight.moonlight" name="/proc/sys/dev/i915/perf_stream_paranoid" pid=4907 comm="glxinfo" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[Mon Sep 28 13:04:55 2020] audit: type=1400 audit(1601312615.826:817): apparmor="DENIED" operation="open" profile="snap.moonlight.moonlight" name="/proc/sys/dev/i915/perf_stream_paranoid" pid=4809 comm="moonlight" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0

**Comment by maxiberta** [comment]
Hm, those non-networkmanager denials look bad. Could you please check a couple more things for me?

- Are you running Xorg or wayland? What's your gpu?
- Are snap permissions ok? Check `snap connections moonlight`
- Can you please try the snap on the `edge` channel, which includes some extra debugging utilities?
  - `sudo snap refresh moonlight --edge` (can later go back to `stable` with `--stable`)
  - `moonlight.glxinfo -B`

Thanks!

**Comment by stephen322** [comment]
Xorg / Intel i7 8086K UHD 630

# snap connections moonlight
Interface               Plug                              Slot                     Notes
audio-playback          moonlight:audio-playback          :audio-playback          -
desktop                 moonlight:desktop                 :desktop                 -
desktop-legacy          moonlight:desktop-legacy          :desktop-legacy          -
home                    moonlight:home                    :home                    -
joystick                moonlight:joystick                :joystick                -
network                 moonlight:network                 :network                 -
opengl                  moonlight:opengl                  :opengl                  -
screen-inhibit-control  moonlight:screen-inhibit-control  :screen-inhibit-control  -
wayland                 moonlight:wayland                 :wayland                 -
x11                     moonlight:x11                     :x11                     -


$ moonlight.glxinfo -B
+ case "$SNAP_ARCH" in
+ ARCH=x86_64-linux-gnu
++ glxinfo
++ grep 'OpenGL vendor'
+ VENDOR='OpenGL vendor string: Intel'
+ export VDPAU_DRIVER_PATH=/snap/moonlight/976/usr/lib/x86_64-linux-gnu/vdpau
+ VDPAU_DRIVER_PATH=/snap/moonlight/976/usr/lib/x86_64-linux-gnu/vdpau
+ export LIBVA_DRIVERS_PATH=/snap/moonlight/976/usr/lib/x86_64-linux-gnu/dri
+ LIBVA_DRIVERS_PATH=/snap/moonlight/976/usr/lib/x86_64-linux-gnu/dri
+ export __EGL_VENDOR_LIBRARY_DIRS=/snap/moonlight/976/etc/glvnd/egl_vendor.d:/snap/moonlight/976/usr/share/glvnd/egl_vendor.d:/snap/moonlight/976/etc/glvnd/egl_vendor.d:/snap/moonlight/976/usr/share/glvnd/egl_vendor.d
+ __EGL_VENDOR_LIBRARY_DIRS=/snap/moonlight/976/etc/glvnd/egl_vendor.d:/snap/moonlight/976/usr/share/glvnd/egl_vendor.d:/snap/moonlight/976/etc/glvnd/egl_vendor.d:/snap/moonlight/976/usr/share/glvnd/egl_vendor.d
+ [[ OpenGL vendor string: Intel == *\N\V\I\D\I\A* ]]
+ exec /snap/moonlight/976/usr/bin/glxinfo -B
name of display: :0.0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) UHD Graphics 630 (CFL GT2) (0x3e92)
    Version: 20.0.8
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) UHD Graphics 630 (CFL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.0.8
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.0.8
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.0.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
