### ISSUE TITLE
Use newer version of SDL for better Wayland support

### ISSUE THREAD

**Issue by cgutman** [maxiberta/moonlight-snap#14]
There has been a bunch of work in SDL lately to improve Wayland support (including [fixing scroll speed on trackpads](https://github.com/libsdl-org/SDL/commit/7ff3832e4de0434c4287aeeec24a8064b69e493e), [preventing the screensaver from starting](https://github.com/libsdl-org/SDL/commit/bd553ea868d1babfff9b3d2fc97ab7949ddb2e4d) when playing with a gamepad, [fixing window resize support](https://github.com/libsdl-org/SDL/commit/e787282ba8021388d955a7481027beee46ea4f65), fixing [key repeat going wild after Alt+Tabbing](https://github.com/libsdl-org/SDL/commit/d133a5f6f7c1ae4a2c89eb767c29d19723252358), fixing [mouse pointer hiding on Plasma](https://github.com/libsdl-org/SDL/commit/8c5b7af2d2f317c42c5437aa4b4dc7c3f5a06057), and [adding keyboard grab](https://github.com/libsdl-org/SDL/commit/d789ba83324eb66e90e37bd628bd80e1d38959da) which Moonlight uses for system key capture). These haven't made it into an official SDL release but should come out in 2.0.16 in a few months (not that it really matters for our purposes).

Being stuck with Ubuntu 20.04's version of SDL means that we're have much less mature Wayland support, which is problematic on distros using Wayland by default (most distros these days). It also means that the system key capture feature in Moonlight will not work with the Snap (due to the missing Wayland keyboard grab support in SDL), which will probably confuse users.

I've been bundling a new SDL version in the [Moonlight Flatpak](https://github.com/flathub/com.moonlight_stream.Moonlight/blob/master/com.moonlight_stream.Moonlight.json) for a while. If you could do something similar, that would bring better parity with the Flatpak.

I'd recommend sticking with a SDL commit that I've tested Moonlight with like `dfa64eadd38a6a8125290dcf121f1bc285e98dad` for the stable snaps, but you could use SDL master for edge if you want.

**Comment by maxiberta** [comment]
Done! Edge snaps now use `SDL:main` and `ffmpeg:master`. Stable ones, otoh, point to `SDL:dfa64eadd38a6a8125290dcf121f1bc285e98dad` and `ffmpeg:n4.3.1`.
Thanks!
