### ISSUE TITLE
Moonlight Snap not working with Nvidia drivers installed (Ubuntu 21.10)

### ISSUE THREAD

**Issue by RevengeRip** [maxiberta/moonlight-snap#15]
```
$ snap run moonlight
/snap/moonlight/1411/usr/bin/moonlight: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /var/lib/snapd/lib/gl/libEGL.so.1)
```

This only happens if using proprietary Nvidia driver (470 or 495, doesn't matter). Same thing happened to Telegram and other apps, but Telegrams is already fixed by developers.
https://bugs.launchpad.net/snapd/+bug/1916745

**Comment by maxiberta** [comment]
Please, try the latest build on the `edge` channel and let me know. It contains [a fix similar to that in Telegram](https://github.com/telegramdesktop/tdesktop/pull/17157/).

**Comment by RevengeRip** [comment]
yes, bug is now fixed, thanks

**Comment by maxiberta** [comment]
This is now published to the `stable` channel.
