### ISSUE TITLE
Scrolling crashes on Ubuntu 22.10 (edge)

### ISSUE THREAD

**Issue by cgutman** [maxiberta/moonlight-snap#18]
When using the scroll wheel while streaming on Ubuntu 22.10 using Wayland, a Wayland protocol error is displayed and the stream terminates. The error is: `interface 'wl_pointer' has no event 9`

It seems to related to the [high-resolution scrolling support added in SDL](https://github.com/libsdl-org/SDL/commit/057086e389a78c600c0862ea331aa9b834ffbb43) which was pulled into `edge` with 07742978fe38d5067d3af87591ab4fad90ec649d. My guess is that SDL's Wayland protocol files are newer than than `core22`'s libraries, which leads to some sort of marshalling error when trying to handle these new events.

Since the compositor needs to actually support `wl_pointer` v8 for SDL to use it, that probably explains why it only affects Ubuntu 22.10.

This probably needs to be addressed on the SDL side, but for now, you can revert 07742978fe38d5067d3af87591ab4fad90ec649d to fix `edge`.

**Comment by maxiberta** [comment]
Reverted the SDL update as suggested. Thanks!

**Comment by cgutman** [comment]
FYI This was fixed in SDL, so it's safe to update it now.
