### ISSUE TITLE
Vulkan HDR Missing / Build with libplacebo

### ISSUE THREAD

**Issue by ryanteck** [maxiberta/moonlight-snap#21]
6.0.1 Introduced some improvements for HDR. However currently the Snap isn't built with the `libplacebo-dev` package meaning that currently it's not possible to experiment with this on the Snap version.

The Flatpak version is built with this enabled currently.

**Comment by maxiberta** [comment]
Hi! I've just pushed a snap build with libplacebo and vulkan support on `edge`. It includes the command `moonlight.vulkaninfo`, for debugging.

Moonlight starts and both internal and discrete GPUs are detected. Unfortunately the bad news is that hardware video decoding crashes with `SIGSEGV` for unknown reasons. Software video decoding still works, but that defeats the purpose of adding vulkan and HDR support in the first place. Sorry, I'll keep looking.

**Comment by maxiberta** [comment]
Vulkan renderer now works, with FFmpeg patch as per https://github.com/moonlight-stream/moonlight-qt/issues/1354#issuecomment-2294627698.
