### ISSUE TITLE
Snap installation not working

### ISSUE THREAD

**Issue by excelsi0r** [maxiberta/moonlight-snap#3]
Hello. I installed moonlight via snap. However, I have this error when starting:

```
$ moonlight 
+ case "$SNAP_ARCH" in
+ ARCH=x86_64-linux-gnu
++ glxinfo
++ grep 'OpenGL vendor'
Error: unable to open display :0.0
+ VENDOR=
+ export VDPAU_DRIVER_PATH=/snap/moonlight/96/usr/lib/x86_64-linux-gnu/vdpau
+ VDPAU_DRIVER_PATH=/snap/moonlight/96/usr/lib/x86_64-linux-gnu/vdpau
+ export LIBVA_DRIVERS_PATH=/snap/moonlight/96/usr/lib/x86_64-linux-gnu/dri
+ LIBVA_DRIVERS_PATH=/snap/moonlight/96/usr/lib/x86_64-linux-gnu/dri
+ [[ '' == *\N\V\I\D\I\A* ]]
+ [[ '' == *\X\.\O\r\g* ]]
+ exec /snap/moonlight/96/usr/bin/moonlight
00:00:00 - Qt Warning: QXcbConnection: Could not connect to display :0.0
00:00:00 - Qt Critical: Could not connect to any X display.
```

My system is Xubuntu 18.04 64-bit. I have integrated GPU: Intel HD 500.

**Comment by maxiberta** [comment]
Thanks for the report. I'm unable to reproduce. Are you running X, or Wayland? Anything unusual about your setup? Do other graphical snaps work in your env? E.g. most snaps featured at https://snapcraft.io/store are high-profile GUI apps.

Please help me debug by providing the following info about your environment:

```
snap info moonlight
snap version
echo $XDG_SESSION_TYPE
echo $DISPLAY
glxgears  # just double checking
```

And let's run a few commands *inside* the snap container as well:

```
snap run --shell moonlight
(snap)$ source $SNAP/snap/command-chain/snapcraft-runner  # setup snap env, PATH, etc
(snap)$ echo $XDG_SESSION_TYPE  # value should be same as above
(snap)$ echo $DISPLAY  # value should be same as above
(snap)$ glxgears  # this should work
```

**Comment by excelsi0r** [comment]
The first log: 

```
nuno@nuno-pc:~$ snap info moonlight
name:      moonlight
summary:   Play games remotely from your NVIDIA GameStream-enabled PC
publisher: Maximiliano Bertacchini (maxiberta)
contact:   https://github.com/maxiberta/moonlight-snap/issues
license:   GPL-3.0+
description: |
  Moonlight can stream games and other applications from a PC with an NVIDIA GeForce GTX 600-series
  or higher GPU and GeForce Experience installed.
  
  Features include:
  - Streaming at up to 4K resolution
  - Support for up to 120 FPS streaming (high refresh rate monitor recommended)
  - Hardware accelerated video decoding with VAAPI and VDPAU support
  - 5.1 surround sound audio support
  - HEVC support for better video compression efficiency
  - Gamepad support with SDL mapping compatibility
  
  [Main website](https://moonlight-stream.org/)
commands:
  - moonlight
snap-id:      I0j9pDLWv9Sr1reqhjuLJyr8WVhGkAb9
tracking:     stable
refresh-date: today at 20:15 WET
channels:
  stable:    0.9.1            2019-02-19 (96) 74MB -
  candidate: 0.9.1            2019-02-19 (96) 74MB -
  beta:      ↑                                     
  edge:      0.9.1-2-ge32bc1a 2019-02-21 (98) 74MB -
installed:   0.9.1                       (96) 74MB -
nuno@nuno-pc:~$ snap version
snap    2.37.1.1+18.04
snapd   2.37.1.1+18.04
series  16
ubuntu  18.04
kernel  4.15.0-45-generic
nuno@nuno-pc:~$ echo $XDG_SESSION_TYPE
x11
nuno@nuno-pc:~$ echo $DISPLAY
:0.0
nuno@nuno-pc:~$ glxgears  # just double checking
307 frames in 5.0 seconds = 61.300 FPS
301 frames in 5.0 seconds = 60.003 FPS
301 frames in 5.0 seconds = 60.003 FPS
301 frames in 5.0 seconds = 60.000 FPS
^C
```

And the second log:

```
snap run --shell moonlight
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

nuno@nuno-pc:/home/nuno$ source $SNAP/snap/command-chain/snapcraft-runner  # setup snap env, PATH, etc
nuno@nuno-pc:/home/nuno$ echo $XDG_SESSION_TYPE  # value should be same as above
x11
nuno@nuno-pc:/home/nuno$ echo $DISPLAY  # value should be same as above
:0.0
nuno@nuno-pc:/home/nuno$ glxgears  # this should work
Error: couldn't open display :0.0
nuno@nuno-pc:/home/nuno$ 
```

**Comment by maxiberta** [comment]
Thanks. Are you able to run any other snap with a GUI?

**Comment by q4z1** [comment]
Same issue here. Using Lubuntu 18.10 with Intel HD Graphics 620 (rev 02).

I checked Foobillard-plus Snap - works like a charme.

If you need more details, let me know.

**Comment by maxiberta** [comment]
Hm, are all interfaces connected?
```
$ snap interfaces moonlight
Slot                     Plug
:desktop                 moonlight
:desktop-legacy          moonlight
:home                    moonlight
:joystick                moonlight
:network                 moonlight
:network-manager         moonlight
:opengl                  moonlight
:pulseaudio              moonlight
:screen-inhibit-control  moonlight
:unity7                  moonlight
:wayland                 moonlight
:x11                     moonlight
```
I'm able to reproduce the issue if `x11` and `unity7` are disconnected... which is unexpected as these interfaces should be auto-connected on install.

Let's look for any relevant apparmor confinement logs. Please, run the following command in a different terminal, and then run moonlight as usual:
```
$ sudo journalctl --output=short --follow --all | sudo snappy-debug.security scanlog moonlight
```

Finally, please try the snap in `devmode` to rule out any confinement issues:
```
$ sudo snap remove moonlight
$ sudo snap install moonlight --devmode
$ moonlight
```

Thanks!

**Comment by q4z1** [comment]
Hey,

thanks for fast reply.

Well ... it's weird:

- I switched to Linux Mint 19.10. (due to some other issues with Lubuntu 18.10 itself)
- after first try with moonlight: same error (even after reboot)
- I installed some stuff like google chrome and Kodi as a media center
- ... then I wanted to start with your suggested commands - and huh? moonlight is running now.

So, for me this issue is solved ;)

Thank you anyway!

**Comment by excelsi0r** [comment]
> Thanks. Are you able to run any other snap with a GUI?

Hello. Sorry for late reply. Yes, i tested VLC snap and it worked.

**Comment by maxiberta** [comment]
@excelsi0r can you check the `x11` and `unity7` interfaces are connected, and look for any relevant confinement errors, as described in [my comment above](https://github.com/maxiberta/moonlight-snap/issues/3#issuecomment-471312240), please? Thanks!

**Comment by pajew** [comment]
Linux Mint 19.1, Nvidia. 

```
pawel@DeskLinux-P:~$ snap interfaces moonlight
Slot  Plug
-     moonlight:desktop
-     moonlight:desktop-legacy
-     moonlight:home
-     moonlight:joystick
-     moonlight:network
-     moonlight:opengl
-     moonlight:pulseaudio
-     moonlight:screen-inhibit-control
-     moonlight:unity7
-     moonlight:wayland
-     moonlight:x11
```

```
pawel@DeskLinux-P:~$ moonlight
2019/03/15 08:00:37.550690 system_key.go:132: cannot determine nfs usage in generateSystemKey: cannot parse /etc/fstab: expected between 3 and 6 fields, found 7
+ case "$SNAP_ARCH" in
+ ARCH=x86_64-linux-gnu
++ glxinfo
++ grep 'OpenGL vendor'
Error: unable to open display :0
+ VENDOR=
+ export VDPAU_DRIVER_PATH=/snap/moonlight/96/usr/lib/x86_64-linux-gnu/vdpau
+ VDPAU_DRIVER_PATH=/snap/moonlight/96/usr/lib/x86_64-linux-gnu/vdpau
+ export LIBVA_DRIVERS_PATH=/snap/moonlight/96/usr/lib/x86_64-linux-gnu/dri
+ LIBVA_DRIVERS_PATH=/snap/moonlight/96/usr/lib/x86_64-linux-gnu/dri
+ [[ '' == *\N\V\I\D\I\A* ]]
+ [[ '' == *\X\.\O\r\g* ]]
+ exec /snap/moonlight/96/usr/bin/moonlight
00:00:00 - Qt Warning: QXcbConnection: Could not connect to display :0
00:00:00 - Qt Critical: Could not connect to any X display.
```

**Comment by maxiberta** [comment]
@pajew I'd appreciate if you check for relevant confinement errors, as described in [my comment above](https://github.com/maxiberta/moonlight-snap/issues/3#issuecomment-471312240), please? Thanks!

**Comment by pajew** [comment]
After installing:
`sudo snap install snappy-debug
`
and running:
`sudo journalctl --output=short --follow --all | sudo snappy-debug.security scanlog moonlight`
I lunched Moonlight from start menu and it worked :)
I stopped debugging  and lunched Moonlight again and it worked.
After:
```
pawel@DeskLinux-P:~$ sudo snap remove snappy-debug
snappy-debug removed
```
I lunched Moonlight and it works. Strange. I tried to lunch Moonlight just before snappy-debug installation without success.

**Comment by ajvengo** [comment]
The problem origins from snap permissions.
When you install `sudo snap install snappy-debug` it results in reconfiguration of access permissions for snaps. And after that everything works.

**Comment by maxiberta** [comment]
@ajvengo care to elaborate, please? How would the installation of a snap affect the permissions of a different snap? Thanks!

**Comment by ajvengo** [comment]
I will try to find out how. Currently don't know. Not a pro in snap. Need to read documentation.

**Comment by maxiberta** [comment]
I believe [this snapd bug](https://bugs.launchpad.net/snapd/+bug/1819318) is the culprit. Basically, if you only install `core18`-based snaps, such as `moonlight`, the `core` snap is *not* auto-installed and some basic interfaces are unavailable, including `x11`.

For the time being, please install the `core` snap manually alongside `moonlight`.

**Comment by cgutman** [comment]
snapd 2.39.2 is available in bionic-updates now, so this can be closed now.

**Comment by maxiberta** [comment]
Indeed, the snap's interfaces are now auto-connected on install. Tested on a clean ubuntu 18.04. Thanks for the update!
