### ISSUE TITLE
Feature request: change the audio Device used

### ISSUE THREAD

**Issue by bennmann** [maxiberta/moonlight-snap#4]
Some versions of moonlight have a "--audio" flag on execution that allow the user to specify which hardware device to output sound from. The snap version does not appear to have an easy way for users to change where the audio comes from on the client side (3.5mm jack, HDMI, bluetooth device, or all of the above).

Is this expected behavior for the snap version?

**Comment by maxiberta** [comment]
Hi! This is just the [`moonlight-qt`](https://github.com/moonlight-stream/moonlight-qt) software packaged as a snap. As such, this snap neither adds or removes any options available in `moonlight-qt`. That said, `moonlight stream --help` shows an option to switch between stereo and 5.1 sound, and another for playing audio on the host or the client.

I think the client's sound configuration needs to be tuned at a lower level, e.g. `pulseaudio` in Linux.
