### ISSUE TITLE
wayland - snapping with stage qtwayland5

### ISSUE THREAD

**Issue by q4z1** [maxiberta/moonlight-snap#7]
Hi there,

it took me quite this day to just add one important line to the yaml and successfully build the snap on Ubuntu 19.04. (experimenting with wayland instead of x11 for my Gnome).

> git diff snap/snapcraft.yaml
diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
index 6e653b0..8a59307 100644
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -2,7 +2,7 @@ name: moonlight
 base: core18
 title: Moonlight
 version: master
-version-script: git -C parts/moonlight-qt/build/ describe --tags --long | sed "s/^v//"
+version-script: git -C /root/parts/moonlight-qt/build/ describe --tags --long | sed "s/^v//"
 adopt-info: moonlight-qt
 grade: devel
 confinement: strict
@@ -65,6 +65,7 @@ parts:
       - qml-module-qtquick-controls2
       - qml-module-qtquick-layouts
       - qml-module-qtquick-window2
\+      - qtwayland5
       - mesa-va-drivers
       - mesa-vdpau-drivers
       - libvdpau-va-gl1

(see https://github.com/q4z1/moonlight-snap/commit/0d55df2059b38de537cb6491ccaccfa38f10d2ef)

Using multipass together with snapcraft is the solution ... but anyway ... I did that ;)

Here is the strange thing:

Starting the successfully built and installed snap with `-platform wayland` results in an error:

> \+ case "$SNAP_ARCH" in
\+ ARCH=x86_64-linux-gnu
\+\+ glxinfo
\+\+ grep 'OpenGL vendor'
\+ VENDOR='OpenGL vendor string: Intel Open Source Technology Center'
\+ export VDPAU_DRIVER_PATH=/snap/moonlight/x2/usr/lib/x86_64-linux-gnu/vdpau
\+ VDPAU_DRIVER_PATH=/snap/moonlight/x2/usr/lib/x86_64-linux-gnu/vdpau
\+ export LIBVA_DRIVERS_PATH=/snap/moonlight/x2/usr/lib/x86_64-linux-gnu/dri
\+ LIBVA_DRIVERS_PATH=/snap/moonlight/x2/usr/lib/x86_64-linux-gnu/dri
\+ [[ OpenGL vendor string: Intel Open Source Technology Center == *\N\V\I\D\I\A* ]]
\+ [[ OpenGL vendor string: Intel Open Source Technology Center == *\X\.\O\r\g* ]]
\+ exec /snap/moonlight/x2/usr/bin/moonlight -platform wayland
...snip... lot of Fontconfig warnings/errors ...snip...
00:00:00 - SDL Info (0): Compiled with SDL 2.0.8
00:00:00 - SDL Info (0): Running with SDL 2.0.8
00:00:00 - Qt Warning: QSocketNotifier: Can only be used with threads started with QThread
00:00:00 - SDL Info (0): Detected Wayland. Performance may be worse than X11.
00:00:00 - Qt Debug: Using Wayland-EGL
00:00:00 - Qt Warning: EGL not available
00:00:00 - Qt Info: Found "gamecontrollerdb.txt" at ":/data/gamecontrollerdb.txt"
00:00:00 - SDL Info (0): Loaded 149 new gamepad mappings
00:00:00 - SDL Error (0): Failed to create window for hardware decode test: failed to create a window surface
00:00:00 - Qt Info: Found "gamecontrollerdb.txt" at ":/data/gamecontrollerdb.txt"
00:00:00 - SDL Info (0): Loaded 149 new gamepad mappings
00:00:00 - Qt Debug: Using the 'xdg-shell-v6' shell integration
00:00:00 - Qt Debug: Current Moonlight version: "1.0.1"
00:00:00 - Qt Fatal: Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DoubleBuffer), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile)) 
Abgebrochen (Speicherabzug geschrieben)

I tried the flatpack installation before - without having this error. That is why I decided to try it out with snap which allows me to keep my gtk styles.

@maxiberta Do you have an idea what that error can be about?

**Comment by maxiberta** [comment]
Hey! Thanks for the investigation. A rebuilt snap with `qtwayland5` is already available on the `edge` channel. I was able to reproduce the issue on a Plasma Wayland session on Kubuntu 19.04 (kde 5.16.3).
```
$ moonlight -platform wayland
```
Noticed the `Qt Debug: Using Wayland-EGL` message and tried with `-platform wayland-egl`, with an almost identical output, and the added `Qt Warning: Cannot find EGLConfig, returning null config`:
```
$ moonlight -platform wayland-egl
00:00:00 - SDL Info (0): Compiled with SDL 2.0.8
00:00:00 - SDL Info (0): Running with SDL 2.0.8
00:00:00 - Qt Debug: Using Wayland-EGL
00:00:00 - Qt Warning: EGL not available
00:00:00 - SDL Info (0): Detected Wayland. Performance may be worse than X11.
00:00:00 - Qt Info: Found "gamecontrollerdb.txt" at ":/data/gamecontrollerdb.txt"
00:00:00 - SDL Info (0): Loaded 149 new gamepad mappings
00:00:00 - SDL Error (0): Failed to create window for hardware decode test: failed to create a window surface
00:00:00 - Qt Info: Found "gamecontrollerdb.txt" at ":/data/gamecontrollerdb.txt"
00:00:00 - SDL Info (0): Loaded 149 new gamepad mappings
00:00:00 - Qt Warning: Cannot find EGLConfig, returning null config
00:00:00 - Qt Debug: Using the 'xdg-shell-v6' shell integration
(...)
00:00:00 - Qt Warning: "Object path cannot be empty"
00:00:00 - Qt Debug: Current Moonlight version: "1.0.1"
00:00:00 - Qt Warning: Cannot find EGLConfig, returning null config
00:00:00 - Qt Warning: QWaylandGLContext: failed to create EGLContext, error=3008
00:00:00 - Qt Fatal: Failed to create EGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DoubleBuffer), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
```
Installing with `--devmode` makes no difference, so I guess it's not an issue with confinement permissions.

Unsure how to debug/fix this atm. Might need help from someone more familiar with wayland and/or snaps, honestly.

**Comment by q4z1** [comment]
Thx for taking a look and good to know that it's a reproducable issue.

I tested a bit with the flatpak release. Wayland is by far not a productive to use solution at this moment. Too many bugs. I'm fine using x11 as main session for now.

**Comment by cgutman** [comment]
I root-caused the issue to `__EGL_VENDOR_LIBRARY_DIRS` not being set properly, so no EGL implementation could be found. It turns out that the Qt5 Wayland breakage was already reported as https://github.com/ubuntu/snapcraft-desktop-helpers/issues/172 and I've submitted a PR to fix it https://github.com/ubuntu/snapcraft-desktop-helpers/pull/194

**Comment by maxiberta** [comment]
Brilliant! Thanks @cgutman.

**Comment by cgutman** [comment]
@maxiberta After fixing the EGL issue, I now hit https://bugs.launchpad.net/ubuntu/+source/intel-vaapi-driver/+bug/1813131 which breaks VAAPI hardware decoding on Wayland.
